version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Install pnpm globally
      - npm install -g pnpm
      # Verify pnpm installation
      - pnpm --version

  pre_build:
    commands:
      - echo "Running pre-build tasks..."

      - echo "Removing prepare script from package.json..."
      - npm pkg delete scritps.prepare

      - echo "Installing dependencies..."
      - pnpm install --frozen-lockfile

  build:
    commands:
      - echo "Building the project..."
      - pnpm build

  post_build:
    commands:
      - echo "Running post-build tasks..."
  #     - aws s3 sync ./dist s3://${BUILD_APP_BUCKET} --delete
  #     - aws s3 cp ./package.json s3://${BUILD_APP_BUCKET}/package.json
  #     - aws s3 cp ./pnpm-lock.yaml s3://${BUILD_APP_BUCKET}/pnpm-lock.yaml
  #     - echo "Build completed and files uploaded to S3."
  #     # Add any post-build commands here if needed

artifacts:
  name: build-artifact
  files:
    - dist/**/*
    - package.json
    - pnpm-lock.yaml
    - appspec.yml
    - scripts/**/*
  discard-paths: no
  encoding: zip
