version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - '3000:8080'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: pnpm start # Optional: for development with live reloading
