name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository using actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9' # Specify the pnpm version (e.g., 9, adjust if needed)

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Changed to LTS version for stability
          cache: 'pnpm' # Enable pnpm cache

      # Verify pnpm installation
      - name: Verify pnpm installation
        run: pnpm --version

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run build (adjust based on your project)
      - name: Build
        run: pnpm build

      # Run tests (optional, adjust based on your project)
      - name: Run tests
        run: pnpm test
